// <auto-generated />
namespace mtv_management_leave.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddleaveBonus_Remove_Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddleaveBonus_Remove_Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201710090911177_AddleaveBonus_Remove_Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
