//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtv_management_leave.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeaveManagementEntities : DbContext
    {
        public LeaveManagementEntities()
            : base("name=LeaveManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddLeave> AddLeaves { get; set; }
        public virtual DbSet<DataBeginYear> DataBeginYears { get; set; }
        public virtual DbSet<DataInOutRaw> DataInOutRaws { get; set; }
        public virtual DbSet<InOut> InOuts { get; set; }
        public virtual DbSet<LeaveMonthly> LeaveMonthlies { get; set; }
        public virtual DbSet<MasterLeaveDayCompany> MasterLeaveDayCompanies { get; set; }
        public virtual DbSet<MasterLeaveType> MasterLeaveTypes { get; set; }
        public virtual DbSet<RegisterLeave> RegisterLeaves { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserSeniority> UserSeniorities { get; set; }
    }
}
