//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtv_management_leave.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveMonthly
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public System.DateTime Month { get; set; }
        public Nullable<byte> LeaveAvailable { get; set; }
        public Nullable<byte> LeaveUsed { get; set; }
        public Nullable<byte> LeaveRemain { get; set; }
        public Nullable<byte> LeaveNonPaid { get; set; }
        public Nullable<bool> IsMaterityLeave { get; set; }
        public int UserCreated { get; set; }
        public int UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual User User { get; set; }
    }
}
