//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtv_management_leave.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterLeave
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public int LeaveTypeId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<double> RegisterHour { get; set; }
        public string Reason { get; set; }
        public System.DateTime DateRegister { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> UserApprove { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public int UserCreated { get; set; }
        public int UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual MasterLeaveType MasterLeaveType { get; set; }
        public virtual User User { get; set; }
    }
}
